### ISSUE TITLE
All session properties should be converted to strings

### ISSUE THREAD

**Issue by orestis** [toyokumo/tarayo#12]
According to https://jakarta.ee/specifications/mail/1.6/apidocs/com/sun/mail/smtp/package-summary.html, 

> The properties are always set as strings; the Type column describes how the string is interpreted. For example, use
>
>        props.put("mail.smtp.port", "888");
> to set the mail.smtp.port property, which is of type int.

Currently tarayo converts only booleans AFAICT.

It also would be nice to expose some convenience timeout properties...

**Comment by liquidz** [comment]
@orestis Thanks for your reporting!

> The properties are always set as strings; the Type column describes how the string is interpreted. For example, use

Oh I overlooked it.
But for example,  `mail.smtp.ssl.socketFactory` seems to be required putting an instance of a class.
So we should convert only `int` to `string` additionally.

**Comment by liquidz** [comment]
Fixed by d7e6383
