### ISSUE TITLE
Creating custom message id throws ClassCastException

### ISSUE THREAD

**Issue by dafuqislv** [toyokumo/tarayo#17]
I'm having trouble trying to use **:message-id-fn** as it always throw an **ClassCastException**. How can I use it correctly? 

### Trying to use a string: 
```
(tarayo/send! conn {... :message-id-fn "xyz.1234@example.com"})

java.lang.ClassCastException: class java.lang.String cannot be cast to class clojure.lang.IFn (java.lang.String is in module java.base of loader 'bootstrap'; clojure.lang.IFn is in unnamed module of 
loader 'app')
```

### Trying to use a function
```
(tarayo/send! conn {... :message-id-fn (constantly "xyz.1234@example.com") })

java.lang.ClassCastException: class clojure.core$constantly$fn__5689 cannot be cast to class java.lang.String (clojure.core$constantly$fn__5689 is in unnamed module of loader 'app'; java.lang.String 
is in module java.base of loader 'bootstrap')
```

**Comment by liquidz** [comment]
@dafuqislv Thanks for your reporting!
Sorry, it is a simply bug.
`:message-id-fn (constantly "xyz.1234@example.com")` should work, so I fixed the problem in [develop](https://github.com/toyokumo/tarayo/tree/develop) branch.

Could you try?

**Comment by dafuqislv** [comment]
It's fixed now and working as expected 

Thanks!!
